checking system deps

diff --git a/gov b/gov
--- a/gov
+++ b/gov
@@ -36,6 +36,30 @@ assert-system-requirements() {
     err "unsupported os/arch: $OSTYPE/$(uname -m)."
     exit 1
   fi
+
+  local has_missing=
+  local tmp_check_out=
+
+  for dep in wget gunzip tar; do
+    tmp_check_out=$(
+      set +e
+      set +o pipefail
+
+      which "$dep" &> /dev/null
+      if [ "$?" -ne 0 ]; then
+        echo 1
+      fi
+    )
+
+    if [ ! -z "$(echo -n $tmp_check_out)" ]; then
+      err "missing dependency: $dep"
+      has_missing=1
+    fi
+  done
+
+  if [ ! -z "$has_missing" ]; then
+    exit 1
+  fi
 }
 
 #=== FUNCTION =================================================================
